### ISSUE TITLE
There is no direction text when the radial dial is around ~0 degrees.

### ISSUE THREAD

**Issue by ehharvey** [kstencell/CSCN72030-Sec1-Group1#20]
The direction dial looks fanastic! It behaves mostly correct.

However, when the dial is manually set to 0 degrees, it displays something like:

![image](https://user-images.githubusercontent.com/36806437/143689661-ba8e3b1f-a83c-465f-8aa3-eeb6a731aa1b.png)

No assignees yet, but I will tackle it when I have the time.

**Comment by ehharvey** [comment]
It looks like this issue isn't localized to just 0 degrees. This occurs when the dial is set to seemingly random values.

**Comment by ehharvey** [comment]
![image](https://user-images.githubusercontent.com/36806437/143719609-2f75d6db-0a00-46e3-b3e9-933aec88105c.png)

**Comment by kstencell** [comment]
I really should get better at making threads for these bugs that you're finding because I am aware of this one too.

It's getting the better of me and this might not get fixed before the final demo is due.

**Comment by ehharvey** [comment]
Agreed. I'll tackle it for a little while but will dismiss it if it becomes too complicated.

I believe the issue is something to do with this:
`
                this.Dispatcher.Invoke(() =>
                {
                    rotationText.Text = "DIRECTION: " + ((int)((angle * 180.0) / Math.PI)).ToString() + "°";
                });
`
(line 498 in `MainWindow.xaml.cs`).

I'm thinking To.String() is behaving contrary to what we want (e.g., returning an empty string). I'm not sure why the degree symbol is also being omitted though.

**Comment by ehharvey** [comment]
I was mistaken (and the dropped degree symbol _was_ relevant! It turns out the GUI label was simply too small to fit the text sometimes (width-wise). The behaviour of the GUI seems to be `drop the longest string of text (without spaces)`. So at some points (e.g., around 360 degrees), the text was simply too long to be displayed. The degree symbol was also dropped because there was no space between our numerical value and the degree symbol.


Fix is easy. I've widened the label width. Seems to be working as expected now.
