### ISSUE TITLE
Speed text displays 1000 km/s at app start

### ISSUE THREAD

**Issue by ehharvey** [kstencell/CSCN72030-Sec1-Group1#21]
When the application first starts, the speed text displays 1000 km/s even though the control is properly set to 0.

![image](https://user-images.githubusercontent.com/36806437/143689707-dbf5c008-953c-4924-9f95-1fd9cd7f221d.png)

This seems like a simple fix, so @pankitthakkar or @tsparks9038 can take a look at it if you're interested.

**Comment by ehharvey** [comment]
I also noticed that when speed changes, the "SPEED" becomes "Speed".

**Comment by ehharvey** [comment]
Fixed both issues. Fix for initial issue was to simply tell the GUI to start the system with the text label set as "SPEED: 0 KM/S"

**Comment by kstencell** [comment]
Whoops. That was a remnant of the GUI thread. I put it to 1000 because it was the longest text possible and I wanted to make sure it fit on the screen.

Great catch.
