### ISSUE TITLE
Should speed controls be disabled when the ship is out of fuel?

### ISSUE THREAD

**Issue by ehharvey** [kstencell/CSCN72030-Sec1-Group1#23]
More of a speculative question. When the ship is out of fuel, it may be worth to completely disable the speed controls. Currently, the user is able to interact with it, but it will rubber band to 0 immediately after user input.

**Comment by kstencell** [comment]
Currently it rubber bands back to the value it was already set at which makes sense - there's no friction.

I played around with disabling UI controls but the isEnabled property of the UI elements doesn't want to play nice when it's changed through code

**Comment by ehharvey** [comment]
Hmm interesting. I've relied on that when handling alarm dismissal, though that is pretty simple case. I'm going to proceed to merge the other fixes first (as they are much higher priority) before taking a look at this

**Comment by ehharvey** [comment]
Implemented. Await PR
